apiVersion: v1
kind: Service
metadata:
  name: client-service
  labels:
    app: tpdocker
spec:
  type: NodePort  # Utilisez LoadBalancer pour Minikube, NodePort pour Docker Desktop
  selector:
    app: tpdocker # Correspond à l'étiquette du Deployment
  ports:
    - protocol: TCP
      port: 3000  # Port interne du Service (au sein du cluster)
      targetPort: 3000  # Port du container où l'application écoute
      nodePort: 30000  # Port externe sur le nœud (dans la plage 30000-3276)