apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  type: NodePort
  selector:
    app: mern-server
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30005 # Nouveau port non utilisé
